apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-app-deployment
  labels:
    app: aws-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-app
  template:
    metadata:
      labels:
        app: aws-app
    spec:
      containers:
      - name: aws-app
        image: $ECR_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
